In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
df = pd.read_csv('SalaryGender.csv')
display(df)
display(df.columns)
df.shape

Salary  Gender  Age  PhD
0    140.0       1   47    1
1     30.0       0   65    1
2     35.1       0   56    0
3     30.0       1   23    0
4     80.0       0   53    1
..     ...     ...  ...  ...
95    18.6       1   26    0
96   152.0       1   56    1
97     1.8       1   28    0
98    35.0       0   44    0
99     4.0       0   24    0

[100 rows x 4 columns]

Index(['Salary', 'Gender', 'Age', 'PhD'], dtype='object')

(100, 4)

In [3]:
salary = np.array(df['Salary'])
gender = np.array(df['Gender'])
age = np.array(df['Age'])
phd = np.array(df['PhD'])

In [4]:
men_with_phd = df[(df['Gender']==1) &( df['PhD']==1)].shape[0]
women_with_phd = df[(df['Gender']==0) &( df['PhD']==1)].shape[0]
print(f"\nMen with PhD: {men_with_phd} \n women with PhD:{women_with_phd}")
# men_with_phd,women_with_phd


Men with PhD: 24 
 women with PhD:15


In [5]:
# 3.	Use SalaryGender CSV file. Store the “Age” and “PhD” columns in one DataFrame and delete the data of all people who don’t have a PhD
age_phd = df[['Age','PhD']]
age_phd = age_phd[age_phd['PhD']==1]
age_phd

Age  PhD
0    47    1
1    65    1
4    53    1
8    44    1
9    63    1
12   60    1
17   47    1
18   66    1
19   45    1
25   66    1
26   36    1
28   51    1
29   65    1
30   45    1
31   52    1
32   54    1
38   34    1
41   58    1
42   77    1
45   48    1
47   49    1
49   65    1
54   49    1
56   61    1
57   43    1
60   66    1
63   56    1
73   71    1
76   69    1
77   58    1
79   32    1
80   33    1
81   32    1
87   42    1
89   51    1
90   71    1
92   55    1
94   55    1
96   56    1

In [6]:
# 4.	Calculate the total number of people who have a PhD degree from SalaryGender CSV file.
total_phd = df[df['PhD']==1].shape[0]
total_phd

39

In [7]:
np.sum(phd)

np.int64(39)

In [8]:
# 5.	How do you Count The Number Of Times Each Value Appears In An Array Of Integers?
#
#
# [0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]
arr = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])
counts = np.bincount(arr)
print(counts)

[4 2 1 1 3 2 0 0 0 1]


In [9]:
arr = np.array( [[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]])
greater_than_5 = arr[arr>5]
greater_than_5

array([ 6,  7,  8,  9, 10, 11])

In [10]:
z = np.random.random((10,10))
min = z.min
max = z.max
print(min,max)

<built-in method min of numpy.ndarray object at 0x000001A0E8146AF0> <built-in method max of numpy.ndarray object at 0x000001A0E8146AF0>


In [11]:
z = np.random.random(30)
print(f"mean value of z is {z.mean()}")

mean value of z is 0.5103809129025476


In [12]:
z = np.arange(0,11)
z[(3<z) & (z<9)]*=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [13]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[3 7 7]
 [5 4 6]
 [3 0 9]]
[[3 0 9]
 [5 4 6]
 [3 7 7]]


In [14]:
z = np.array([[[[1, 6],
         [6, 9]],

        [[1, 2],
         [3, 5]]],


       [[[2, 4],
         [3, 1]],

        [[0, 9],
         [1, 4]]]])
display(z)
print(f" axis =(2,3){np.sum(z,(2,3))}")
print(f" axis =(0,1){np.sum(z,(0,1))}")
print(f" axis =(0){np.sum(z,(0))}")
print(f" axis =(1){np.sum(z,(1))}")
# print(np.sum(z,(1)))

array([[[[1, 6],
         [6, 9]],

        [[1, 2],
         [3, 5]]],


       [[[2, 4],
         [3, 1]],

        [[0, 9],
         [1, 4]]]])

 axis =(2,3)[[22 11]
 [10 14]]
 axis =(0,1)[[ 4 21]
 [13 19]]
 axis =(0)[[[ 3 10]
  [ 9 10]]

 [[ 1 11]
  [ 4  9]]]
 axis =(1)[[[ 2  8]
  [ 9 14]]

 [[ 2 13]
  [ 4  5]]]


In [15]:
# array([[[[1, 6],
#          [6, 9]],
#
#         [[1, 2],
#          [3, 5]]],
#
#
#        [[[2, 4],
#          [3, 1]],
#
#         [[0, 9],
#          [1, 4]]]])
#  axis =(2,3)
# [[22 11]
#  [10 14]]
#
#  axis =(0,1)
# [[ 4 21]
#  [13 19]]
#
#  axis =(0)
# [[[ 3 10]
#   [ 9 10]]
#  [[ 1 11]
#   [ 4  9]]]
#
#  axis =(1)
# [[[ 2  8]
#   [ 9 14]]
#
#  [[ 2 13]
#   [ 4  5]]]


In [22]:
z = np.arange(25).reshape((5,5))
print(z)
z[[0,3]] = z[[3,0]]
print()
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]
 [20 21 22 23 24]]
