In [1]:
import numpy as np

In [2]:
print(np.__version__)
print(np.show_config())

2.3.5
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35219",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.1",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35219",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tire4up4/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib d

c:\Users\gogur\OneDrive\Desktop\Top-Mentor-DS\ML\Case Studies\csenv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [3]:
print(np.info(np.meshgrid))

Return a tuple of coordinate matrices from coordinate vectors.

Make N-D coordinate arrays for vectorized evaluations of
N-D scalar/vector fields over N-D grids, given
one-dimensional coordinate arrays x1, x2,..., xn.

Parameters
----------
x1, x2,..., xn : array_like
    1-D arrays representing the coordinates of a grid.
indexing : {'xy', 'ij'}, optional
    Cartesian ('xy', default) or matrix ('ij') indexing of output.
    See Notes for more details.
sparse : bool, optional
    If True the shape of the returned coordinate array for dimension *i*
    is reduced from ``(N1, ..., Ni, ... Nn)`` to
    ``(1, ..., 1, Ni, 1, ..., 1)``.  These sparse coordinate grids are
    intended to be used with :ref:`basics.broadcasting`.  When all
    coordinates are used in an expression, broadcasting still leads to a
    fully-dimensonal result array.

    Default is False.

copy : bool, optional
    If False, a view into the original arrays are returned in order to
    conserve memory.  Default is T

In [10]:
x = np.array([1,2,3])
x2 = np.array([1,2,3,0])
print(np.all(x))
print(np.all(x2))

True
False


In [17]:
x = np.array([1,9,44,5,0])
print(np.any(np.array([0])))
np.any(x[0])

False


np.True_

In [20]:
a = [np.array([1,0,np.inf,np.nan,-np.inf])]
print(np.isfinite(a))
print(np.isinf(a))
print(np.isnan(a))

[[ True  True False False False]]
[[False False  True False  True]]
[[False False False  True False]]


In [31]:
# 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
a = np.array([1+2j,2+6j,4.5,3,np.nan])
print(np.iscomplex(a))
print(np.isreal(a))
print(np.isscalar([1,2]))

[ True  True False False False]
[False False  True  True  True]
False


In [34]:
x = np.array([3, 5])
y = np.array([2, 5])
print(np.greater_equal(x,y))
print(np.less_equal(x,y))
print(np.less(x,y))

[ True  True]
[False  True]
[False False]


In [5]:
import numpy as np
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x,y))
print(np.allclose(x,y))

[ True  True  True  True  True  True  True  True  True False]
True


In [8]:
x = np.array([1,7,13,105])
print(f"memory occupied by array is: {x.size*x.itemsize} bytes")

memory occupied by array is: 32 bytes


In [11]:
print(np.zeros(10))
print(np.ones(10))
print(np.full(10,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [13]:
print(np.arange(30,71))
print(np.arange(30,71,2))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
