In [2]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.  
import numpy as np
matrix = np.arange(2,11).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [6]:
# Write a NumPy program to convert an array to a float type.  
a=[1,2,3,4,4]
print("Original Array:",a)
float_array = np.array(a,dtype=float)
print(float_array)

Original Array: [1, 2, 3, 4, 4]
[1. 2. 3. 4. 4.]


In [10]:
one_border = np.ones((5,5))
one_border[1:-1,1:-1] = 0
print(one_border)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
z = np.ones((4,4))
z = np.pad(z,(1,1),mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [22]:
chess = np.zeros((8,8))
chess[1::2,::2]=1
chess[::2,1::2]=1
print(chess)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [24]:
print(np.empty((3,3)))
print(np.full((3,2),2))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2 2]
 [2 2]
 [2 2]]


In [28]:
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
centigrade = 5*F/9-5*32/9
print(centigrade)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [30]:
x = np.sqrt([1+2j])
print(x.real)
print(x.imag)


[1.27201965]
[0.78615138]
